//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocspiderTesteUploadDownload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public int IdUpload { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string Arquivo { get; set; }
        public string Nome_Do_Arquivo { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
    }
}
